"""
backend/scoring/sanitize.py

Sanitization helpers that translate internal database codes and enum values
into human-readable strings before they appear in any user-facing text.

All text generated by the scoring engine (explanation, top_risks, titles) MUST
pass through sanitize_title() before it reaches the API response.

Sources of internal codes:
  - Chicago CDOT street closure work_type codes (e.g. "GenOpening", "GenOccupy")
  - Chicago building permit type strings (e.g. "EASY PERMIT PROGRAM")
  - ISO date strings in explanation text
  - Meter distances in text

Frontend maintains a parallel copy of these mappings in
frontend/src/lib/text-sanitize.ts as a defence-in-depth layer.
Keep both files in sync when adding new codes.
"""

from __future__ import annotations

import re
from datetime import date
from typing import Optional


# ---------------------------------------------------------------------------
# Chicago CDOT street closure work_type code → human-readable label
# Source: Socrata jdis-5sry `worktype` field
# ---------------------------------------------------------------------------

WORK_TYPE_LABELS: dict[str, str] = {
    # Confirmed codes seen in production data
    "GenOpening":        "general opening",
    "GenOccupy":         "lane occupation",
    "PartialClosure":    "partial lane closure",
    "FullClosure":       "full street closure",
    "Sidewalk":          "sidewalk work",
    "CurbCut":           "curb cut",
    "Curb":              "curb work",
    "Dumpster":          "dumpster placement",
    "StoragePod":        "storage pod",
    "Crane":             "crane operation",
    "Scaffold":          "scaffolding",
    "Emergency":         "emergency work",
    "Construction":      "construction work",
    "RoadRepair":        "road repair",
    "RoadResurfacing":   "road resurfacing",
    "GasMain":           "gas main work",
    "WaterMain":         "water main work",
    "Sewer":             "sewer work",
    "Electrical":        "electrical work",
    "Filming":           "film/photo permit",
    "SpecialEvent":      "special event",
    "Festival":          "festival",
    "Demonstration":     "demonstration",
    "Moving":            "moving permit",
    "TreeTrimming":      "tree trimming",
    "StreetResurfacing": "street resurfacing",
    "Excavation":        "excavation",
    "Utility":           "utility work",
    "PedestrianAccess":  "pedestrian access work",
    "Loading":           "loading zone work",
    "Parking":           "parking restriction",
    "TrafficControl":    "traffic control",
    "SignalWork":        "traffic signal work",
    "StreetLight":       "street light work",
    "WaterService":      "water service work",
    "SewerRepair":       "sewer repair",
    # Lower-cased variants (Socrata data is inconsistently cased)
    "genopening":        "general opening",
    "genoccupy":         "lane occupation",
    "partialclosure":    "partial lane closure",
    "fullclosure":       "full street closure",
    "sidewalk":          "sidewalk work",
    "emergency":         "emergency work",
    "construction":      "construction work",
    "filming":           "film/photo permit",
    "specialevent":      "special event",
}


# ---------------------------------------------------------------------------
# Chicago building permit type → human-readable label
# These appear in titles after the "PERMIT - " prefix is stripped.
# ---------------------------------------------------------------------------

PERMIT_TYPE_LABELS: dict[str, str] = {
    "EASY PERMIT PROGRAM":             "Minor work permit",
    "SIGNS":                           "Signage permit",
    "WRECKING/DEMOLITION":             "Demolition permit",
    "NEW CONSTRUCTION":                "New construction permit",
    "RENOVATION/ALTERATION":          "Renovation permit",
    "ELECTRIC WIRING":                 "Electrical wiring permit",
    "PLUMBING":                        "Plumbing permit",
    "EXCAVATION":                      "Excavation permit",
    "REINSTATEMENT OF CONDEMNED BLDG": "Reinstatement permit",
    "SCAFFOLDING":                     "Scaffolding permit",
    "BOILER":                          "Boiler permit",
    "ELEVATOR":                        "Elevator permit",
    "FIRE PREVENTION SYSTEM":          "Fire prevention permit",
    "MECHANICAL":                      "Mechanical permit",
    "DRIVEWAY/CURB CUT":              "Driveway/curb cut permit",
    "REVISION":                        "Permit revision",
}


# ---------------------------------------------------------------------------
# Month name lookup for date formatting
# ---------------------------------------------------------------------------

_MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]


def format_date(d: date) -> str:
    """Format a date object as 'Month Day, Year' (e.g. 'March 15, 2024')."""
    return f"{_MONTHS[d.month - 1]} {d.day}, {d.year}"


def format_iso_date(iso: str) -> str:
    """
    Convert an ISO date string (YYYY-MM-DD) to 'Month Day, Year'.
    Returns the original string if it cannot be parsed.
    """
    try:
        year, month, day = iso[:10].split("-")
        return f"{_MONTHS[int(month) - 1]} {int(day)}, {year}"
    except (ValueError, IndexError):
        return iso


# ---------------------------------------------------------------------------
# CamelCase → readable fallback
# Used when a work_type code is not in WORK_TYPE_LABELS.
# "RoadResurfacing" → "road resurfacing"
# ---------------------------------------------------------------------------

_CAMEL_RE = re.compile(r"(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")


def _camel_to_readable(s: str) -> str:
    """Convert a CamelCase identifier to lowercase words."""
    return _CAMEL_RE.sub(" ", s).lower().strip()


# ---------------------------------------------------------------------------
# Work type sanitization
# ---------------------------------------------------------------------------

def sanitize_work_type(code: str) -> str:
    """
    Translate a raw work_type code to a human-readable label.
    Falls back to splitting CamelCase if the code isn't in the table.
    """
    if not code:
        return code
    label = WORK_TYPE_LABELS.get(code) or WORK_TYPE_LABELS.get(code.lower())
    if label:
        return label
    # Unknown code: split CamelCase as a best-effort fallback
    readable = _camel_to_readable(code)
    return readable if readable != code.lower() else code


# ---------------------------------------------------------------------------
# Parenthesized code pattern in titles
# e.g. "(GenOpening)" at the end of "HURON from 900 to 909 (GenOpening)"
# ---------------------------------------------------------------------------

# Parenthesized codes: "(GenOpening)"
_PAREN_CODE_RE = re.compile(
    r"\((" + "|".join(re.escape(k) for k in WORK_TYPE_LABELS) + r")\)",
    re.IGNORECASE,
)

# Bare word codes that stand alone (e.g. notes field "GenOpening; reason text")
_BARE_CODE_RE = re.compile(
    r"\b(" + "|".join(re.escape(k) for k in WORK_TYPE_LABELS) + r")\b",
    re.IGNORECASE,
)

_PAREN_ANY_RE = re.compile(r"\(([A-Z][A-Za-z]+)\)")


def _replace_paren_codes(text: str) -> str:
    """
    Replace parenthesized work type codes with readable labels.
    '(GenOpening)' → '(general opening)'
    Falls back to splitting CamelCase for unknown codes in parentheses.
    """
    def _sub(m: re.Match) -> str:
        code = m.group(1)
        label = sanitize_work_type(code)
        return f"({label})"

    result = _PAREN_CODE_RE.sub(_sub, text)
    # Also handle unknown CamelCase codes in parens
    result = _PAREN_ANY_RE.sub(
        lambda m: f"({_camel_to_readable(m.group(1))})"
        if _camel_to_readable(m.group(1)) != m.group(1).lower() else m.group(0),
        result,
    )
    return result


# ---------------------------------------------------------------------------
# ISO date replacement in prose text
# "active through 2024-03-15" → "active through March 15, 2024"
# ---------------------------------------------------------------------------

_ISO_DATE_RE = re.compile(r"\b(\d{4}-\d{2}-\d{2})\b")


def _replace_iso_dates(text: str) -> str:
    """Replace all ISO date strings in text with human-readable dates."""
    return _ISO_DATE_RE.sub(lambda m: format_iso_date(m.group(1)), text)


# ---------------------------------------------------------------------------
# Street range formatting
# "HURON from 900 to 909" → "Huron between 900–909"
# ---------------------------------------------------------------------------

_RANGE_RE = re.compile(
    r"\b([A-Z0-9][A-Z0-9 ]{1,25})\s+from\s+(\d+)\s+to\s+(\d+)\b",
    re.IGNORECASE,
)


def _replace_ranges(text: str) -> str:
    def _sub(m: re.Match) -> str:
        street = m.group(1).strip().title()
        return f"{street} between {m.group(2)}–{m.group(3)}"

    return _RANGE_RE.sub(_sub, text)


# ---------------------------------------------------------------------------
# ALLCAPS title-case normalization
# "EASY PERMIT PROGRAM at 123 N MAIN ST" → "Easy Permit Program at 123 N Main St"
# Only applies when the string is substantially uppercase.
# ---------------------------------------------------------------------------

def _maybe_title_case(text: str) -> str:
    """Title-case a string that is predominantly uppercase."""
    upper_count = sum(1 for c in text if c.isupper())
    total_alpha = sum(1 for c in text if c.isalpha())
    if total_alpha > 0 and upper_count / total_alpha > 0.7:
        return text.title()
    return text


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def sanitize_title(title: str) -> str:
    """
    Clean a raw project title for user display.

    Applies in order:
      1. Parenthesized work type code replacement
      2. ISO date replacement
      3. Street range reformatting
      4. ALLCAPS → Title Case
    """
    if not title:
        return title
    result = _replace_paren_codes(title)
    result = _replace_iso_dates(result)
    result = _replace_ranges(result)
    result = _maybe_title_case(result)
    return result.strip()


def _replace_bare_codes(text: str) -> str:
    """
    Replace bare (unparenthesized) work type codes in notes text.
    'GenOpening; reason text' → 'general opening; reason text'
    """
    def _sub(m: re.Match) -> str:
        return sanitize_work_type(m.group(1))
    return _BARE_CODE_RE.sub(_sub, text)


def sanitize_notes(notes: Optional[str]) -> Optional[str]:
    """
    Clean raw notes/closure_reason text for user display.
    Notes may contain bare work_type codes (e.g. "GenOpening; some reason")
    rather than parenthesized ones.
    """
    if not notes:
        return notes
    result = _replace_paren_codes(notes)
    result = _replace_bare_codes(result)
    result = _replace_iso_dates(result)
    return result.strip()
