export type SeverityLevel = "LOW" | "MEDIUM" | "HIGH";
export type ConfidenceLevel = "LOW" | "MEDIUM" | "HIGH";
export type ScoreMode = "live" | "demo";

// Structured metadata for a single top-risk contributor (data-024).
// Parallel to the plain-English top_risks strings but machine-readable,
// allowing the frontend to render permit IDs, dates, and source links.
// data-042 adds rewritten_title and rewritten_description: Claude-generated
// clean labels cached in the DB so they are only computed once per project.
export type TopRiskDetail = {
  project_id: string;
  source: string;
  source_id: string;
  title: string;
  impact_type: string;
  distance_m: number;
  start_date: string | null;
  end_date: string | null;
  status: string;
  address: string | null;
  notes?: string | null;
  weighted_score: number;
  // Claude-rewritten display strings (data-042). Present when ANTHROPIC_API_KEY
  // is configured on the backend; null when running in demo mode or when the
  // rewrite call failed.
  rewritten_title?: string | null;
  rewritten_description?: string | null;
  // data-043: richer 4-field display card generated by Claude (or Option A
  // deterministic fallback). Always present when the backend has been updated.
  // display_title supersedes rewritten_title; description supersedes
  // rewritten_description; distance and why_it_matters are new.
  display_title?: string | null;
  distance?: string | null;        // pre-formatted, e.g. "~1,100 ft away"
  description?: string | null;     // factual one-sentence description
  why_it_matters?: string | null;  // practical impact explanation
};

export type ImpactType =
  | "closure_full"
  | "closure_multi_lane"
  | "closure_single_lane"
  | "demolition"
  | "construction"
  | "road_construction"
  | "light_permit"
  // Utility signals (data-046)
  | "utility_outage"
  | "utility_repair"
  // Traffic signal outage (data-038)
  | "traffic_signal_outage"
  // Crime trend signals (data-054)
  | "crime_trend_increasing"
  | "crime_trend_decreasing"
  | "crime_trend_stable";

export type NearbySignal = {
  lat: number;
  lon: number;
  impact_type: ImpactType;
  title: string;
  distance_m: number;
  severity_hint: string;
  weight: number;
  // Optional fields for richer popup display and 30-day forecast
  address?: string | null;
  source?: string;
  start_date?: string | null;
  end_date?: string | null;
};

export type NearbySchool = {
  lat: number;
  lon: number;
  name: string;
  rating: string | null;
  distance_m: number;
};

export type MapNarrationInteraction = "default_load" | "signal_click" | "map_pan";

export type MapNarrationResponse = {
  narration: string | null;
};

export type ScoreResponse = {
  address: string;
  disruption_score: number;
  livability_score?: number;
  livability_breakdown?: {
    weights: Record<string, number>;
    components: Record<string, { raw_score: number; weighted_contribution: number }>;
  };
  confidence: ConfidenceLevel;
  severity: {
    noise: SeverityLevel;
    traffic: SeverityLevel;
    dust: SeverityLevel;
  };
  top_risks: string[];
  explanation: string;
  // Structured per-risk metadata added in data-024. Optional for backward
  // compatibility with backend builds that predate this field.
  top_risk_details?: TopRiskDetail[];
  // Optional for backward compatibility with older backend builds.
  mode?: ScoreMode;
  fallback_reason?: string | null;
  // Coordinates returned by the backend for map display.
  latitude?: number | null;
  longitude?: number | null;
  // Nearby permit/closure signals for the map heat layer.
  nearby_signals?: NearbySignal[];
  // Nearby schools for the school quality map layer (data-061).
  nearby_schools?: NearbySchool[];
};

export type ScoreSource = ScoreMode;

type FrontendFallbackReason =
  | "frontend_api_not_configured"
  | "frontend_network_error"
  | "frontend_backend_error"
  | "frontend_invalid_response";

type LiveScoreResult = {
  score: ScoreResponse;
  source: "live";
  note?: undefined;
};

type DemoScoreResult = {
  score: ScoreResponse;
  source: "demo";
  // Optional because backend 200 demo responses do not add a note,
  // while frontend-fabricated demo fallbacks do.
  note?: string;
};

export type ScoreResult = LiveScoreResult | DemoScoreResult;

const LOCAL_API_URL = "http://127.0.0.1:8000";

export class ApiError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ApiError";
  }
}

function getApiBaseUrl(): string {
  const configuredApiUrl = process.env.NEXT_PUBLIC_API_URL?.trim();

  if (configuredApiUrl) {
    return configuredApiUrl;
  }

  if (process.env.NODE_ENV !== "production") {
    return LOCAL_API_URL;
  }

  return "";
}

function buildApiUrl(pathname: string): URL {
  return new URL(pathname, getApiBaseUrl());
}

function logFrontendFallback(reason: FrontendFallbackReason, message: string) {
  console.warn(`[LRE] frontend demo fallback: ${reason}`);
  return message;
}

// Canonical demo payload used in two places:
// 1. the backend's own demo mode when live scoring is unavailable
// 2. the frontend's fabricated fallback when it cannot reach the backend at all
function buildDemoScore(address: string): ScoreResponse {
  return {
    address,
    disruption_score: 62,
    livability_score: 48,
    livability_breakdown: {
      weights: {
        disruption_risk: 0.35,
        crime_trend: 0.25,
        school_rating: 0.2,
        demographics_stability: 0.1,
        flood_environmental: 0.1,
      },
      components: {
        disruption_risk: { raw_score: 38, weighted_contribution: 13.3 },
        crime_trend: { raw_score: 55, weighted_contribution: 13.8 },
        school_rating: { raw_score: 60, weighted_contribution: 12.0 },
        demographics_stability: { raw_score: 52, weighted_contribution: 5.2 },
        flood_environmental: { raw_score: 40, weighted_contribution: 4.0 },
      },
    },
    confidence: "MEDIUM",
    severity: {
      noise: "LOW",
      traffic: "HIGH",
      dust: "LOW",
    },
    top_risks: [
      "2-lane eastbound closure on W Chicago Ave within roughly 120 meters",
      "Active closure window runs through 2026-03-22",
      "Traffic is the dominant near-term disruption signal at this address",
    ],
    top_risk_details: [],
    explanation:
      "A nearby 2-lane closure is the main driver, so this address has elevated short-term traffic disruption even though noise and dust are limited.",
    mode: "demo",
    fallback_reason: null,
    // Include coordinates for the demo address so the map pin shows immediately.
    latitude: KNOWN_COORDS[address]?.lat ?? null,
    longitude: KNOWN_COORDS[address]?.lon ?? null,
    // Demo heat signals near 1600 W Chicago Ave for map visualisation.
    nearby_signals: [
      {
        lat: 41.8959, lon: -87.6594,
        impact_type: "closure_multi_lane",
        title: "W Chicago Ave 2-lane eastbound closure",
        distance_m: 120, severity_hint: "HIGH", weight: 30.4,
        source: "chicago_closures",
        start_date: "2026-03-15",
        end_date: "2026-03-31",
      },
      {
        lat: 41.8962, lon: -87.6618,
        impact_type: "construction",
        title: "Active construction permit at 1550 W Chicago Ave",
        distance_m: 210, severity_hint: "MEDIUM", weight: 8.8,
        source: "chicago_permits",
        start_date: "2026-02-01",
        end_date: "2026-04-15",
      },
      {
        lat: 41.8948, lon: -87.6602,
        impact_type: "closure_single_lane",
        title: "Curb lane closure on S Ashland Ave",
        distance_m: 380, severity_hint: "MEDIUM", weight: 5.3,
        source: "chicago_closures",
        start_date: "2026-03-20",
        end_date: "2026-03-25",
      },
    ],
  };
}

// Pre-resolved coordinates for the canonical demo/example addresses.
// These are used as an instant fallback when Nominatim is unavailable or slow.
const KNOWN_COORDS: Record<string, { lat: number; lon: number }> = {
  "1600 W Chicago Ave, Chicago, IL": { lat: 41.8956, lon: -87.6606 },
  "700 W Grand Ave, Chicago, IL": { lat: 41.8910, lon: -87.6462 },
  "233 S Wacker Dr, Chicago, IL": { lat: 41.8788, lon: -87.6359 },
};

/**
 * Geocode an address for map display.
 * Checks a local table of known coordinates first (instant, no network).
 * Falls back to Nominatim for arbitrary addresses when a live backend is configured.
 */
export async function geocodeForMap(address: string): Promise<{ lat: number; lon: number } | null> {
  // Fast path: pre-resolved coordinates for demo/example addresses.
  const known = KNOWN_COORDS[address];
  if (known) return known;

  // 1. Live geocoding via Nominatim.
  try {
    const url = new URL("https://nominatim.openstreetmap.org/search");
    url.searchParams.set("q", address);
    url.searchParams.set("format", "json");
    url.searchParams.set("limit", "1");
    url.searchParams.set("countrycodes", "us");
    const resp = await fetch(url.toString(), {
      headers: { "User-Agent": "LivabilityRiskEngine/1.0 (us-mvp)" },
      cache: "no-store",
    });
    if (resp.ok) {
      const data = (await resp.json()) as Array<{ lat: string; lon: string }>;
      if (data.length) {
        return { lat: parseFloat(data[0].lat), lon: parseFloat(data[0].lon) };
      }
    }
  } catch { /* fall through */ }

  // 2. Photon fallback.
  try {
    const url = new URL("https://photon.komoot.io/api/");
    url.searchParams.set("q", address);
    url.searchParams.set("limit", "1");
    url.searchParams.set("lang", "en");
    const resp = await fetch(url.toString(), { cache: "no-store" });
    if (resp.ok) {
      const data = (await resp.json()) as { features: PhotonFeature[] };
      const f = data.features?.[0];
      if (f) {
        const [lon, lat] = f.geometry.coordinates;
        return { lat, lon };
      }
    }
  } catch { /* */ }

  return null;
}

export async function fetchMapNarration(payload: {
  address: string;
  interaction_type: MapNarrationInteraction;
  signals: NearbySignal[];
  top_signal_title?: string;
  clicked_signal?: NearbySignal;
  original_score?: number;
  current_lat?: number;
  current_lon?: number;
}): Promise<MapNarrationResponse> {
  const apiBase = getApiBaseUrl();
  if (!apiBase) return { narration: null };

  try {
    const response = await fetch(new URL("/map/narrate", apiBase), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!response.ok) return { narration: null };
    const data = await response.json();
    return { narration: typeof data?.narration === "string" ? data.narration : null };
  } catch {
    return { narration: null };
  }
}

// Illinois bounding box constants shared by both geocoder calls below.
// Nominatim viewbox: left,top,right,bottom = minLon,maxLat,maxLon,minLat
const _NOMINATIM_VIEWBOX = "-91.5100,42.5100,-87.0200,36.9700";
// Photon bbox: minLon,minLat,maxLon,maxLat
const _PHOTON_BBOX = "-91.5100,36.9700,-87.0200,42.5100";
const _IL_LAT: [number, number] = [36.9700, 42.5100];
const _IL_LON: [number, number] = [-91.5100, -87.0200];
const US_STATE_ABBREVS: Record<string, string> = {
  alabama: "AL",
  alaska: "AK",
  arizona: "AZ",
  arkansas: "AR",
  california: "CA",
  colorado: "CO",
  connecticut: "CT",
  delaware: "DE",
  florida: "FL",
  georgia: "GA",
  hawaii: "HI",
  idaho: "ID",
  illinois: "IL",
  indiana: "IN",
  iowa: "IA",
  kansas: "KS",
  kentucky: "KY",
  louisiana: "LA",
  maine: "ME",
  maryland: "MD",
  massachusetts: "MA",
  michigan: "MI",
  minnesota: "MN",
  mississippi: "MS",
  missouri: "MO",
  montana: "MT",
  nebraska: "NE",
  nevada: "NV",
  "new hampshire": "NH",
  "new jersey": "NJ",
  "new mexico": "NM",
  "new york": "NY",
  "north carolina": "NC",
  "north dakota": "ND",
  ohio: "OH",
  oklahoma: "OK",
  oregon: "OR",
  pennsylvania: "PA",
  "rhode island": "RI",
  "south carolina": "SC",
  "south dakota": "SD",
  tennessee: "TN",
  texas: "TX",
  utah: "UT",
  vermont: "VT",
  virginia: "VA",
  washington: "WA",
  "west virginia": "WV",
  wisconsin: "WI",
  wyoming: "WY",
  "district of columbia": "DC",
};

function _stateAbbrev(raw: string): string {
  if (!raw) return "";
  // ISO 3166-2 format from Nominatim: "US-IL" → "IL"
  if (raw.includes("-")) return raw.split("-").pop()!.toUpperCase();
  return US_STATE_ABBREVS[raw.toLowerCase().trim()] ?? raw.slice(0, 2).toUpperCase();
}

type NominatimItem = {
  lat: string;
  lon: string;
  address: {
    house_number?: string;
    road?: string;
    pedestrian?: string;
    highway?: string;
    city?: string;
    town?: string;
    village?: string;
    state?: string;
    "ISO3166-2-lvl4"?: string;
  };
};

type PhotonFeature = {
  geometry: { coordinates: [number, number] };
  properties: { countrycode?: string; housenumber?: string; street?: string; city?: string; state?: string };
};

/**
 * Extract the bare partial street-name fragment from a raw autocomplete query
 * so results can be post-filtered to only streets that start with that text.
 * e.g. "679 North Pe" → "pe",  "100 W Rand" → "rand"
 */
function _streetPrefix(query: string): string | null {
  let q = query.trim();
  // Strip ", City, ST" or ", ST" patterns (any 2-letter state code).
  q = q.replace(/,\s*[a-z][a-z\s]+,\s*[a-z]{2}\b.*$/i, "");
  q = q.replace(/,\s*[a-z]{2}\b.*$/i, "");
  q = q.replace(/^\d+\s*/, "");
  q = q.replace(/^(?:north|south|east|west|n\.?|s\.?|e\.?|w\.?)\s+/i, "").trim();
  return q.length >= 2 ? q.toLowerCase() : null;
}

function _parseNominatim(items: NominatimItem[], streetFrag?: string | null): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const r of items) {
    const a = r.address;
    const road = a.road ?? a.pedestrian ?? a.highway ?? "";
    if (!road) continue;
    if (streetFrag && !road.toLowerCase().startsWith(streetFrag)) continue;
    const house = a.house_number ?? "";
    const city = a.city ?? a.town ?? a.village ?? "";
    const stateRaw = a["ISO3166-2-lvl4"] ?? a.state ?? "";
    const state = _stateAbbrev(stateRaw);
    const loc = city && state ? `${city}, ${state}` : (city || state || "US");
    const s = house ? `${house} ${road}, ${loc}` : `${road}, ${loc}`;
    if (!seen.has(s)) { seen.add(s); out.push(s); }
  }
  return out.slice(0, 5);
}

function _parsePhoton(features: PhotonFeature[], streetFrag?: string | null): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const f of features) {
    if (f.properties.countrycode?.toUpperCase() !== "US") continue;
    const street = f.properties.street ?? "";
    if (!street) continue;
    if (streetFrag && !street.toLowerCase().startsWith(streetFrag)) continue;
    const house = f.properties.housenumber ?? "";
    const city = f.properties.city ?? "";
    const state = _stateAbbrev(f.properties.state ?? "");
    const loc = city && state ? `${city}, ${state}` : (city || state || "US");
    const s = house ? `${house} ${street}, ${loc}` : `${street}, ${loc}`;
    if (!seen.has(s)) { seen.add(s); out.push(s); }
  }
  return out.slice(0, 5);
}

/**
 * Fetch address suggestions for a partial query.
 *
 * Strategy (in order):
 *  1. Backend /suggest  — server-side Nominatim → Photon; best in production
 *  2. Browser Nominatim — direct from user's browser; bypasses server proxy limits
 *  3. Browser Photon    — fallback if Nominatim is also unreachable from browser
 */
export async function fetchSuggestions(query: string): Promise<string[]> {
  const q = query.trim();
  if (q.length < 3) return [];

  // 0. Static Chicago street list — instant, works offline, no geocoder needed.
  //    Geocoders can't do real-time partial-name matching ("Pe" → Peoria), but
  //    the static list can. Return immediately when we get matches so the
  //    network calls are skipped entirely.
  const { suggestFromStaticList } = await import("./chicago-streets");
  const staticHits = suggestFromStaticList(q);
  if (staticHits.length) return staticHits;

  // Pre-compute the partial street-name fragment for post-filtering results.
  // e.g. "679 North Pe" → "pe" so only streets starting with "pe" (e.g.
  // Peoria) are returned, not Michigan, Milwaukee, etc.
  const streetFrag = _streetPrefix(q);

  // 1. Backend endpoint (tries Nominatim then Photon server-side; already
  //    applies its own street-fragment filter).
  const apiBaseUrl = getApiBaseUrl();
  if (apiBaseUrl) {
    try {
      const url = buildApiUrl("/suggest");
      url.searchParams.set("q", q);
      const resp = await fetch(url.toString(), { cache: "no-store" });
      if (resp.ok) {
        const data = (await resp.json()) as { suggestions: string[] };
        if (data.suggestions?.length) return data.suggestions;
      }
    } catch {
      // Backend unreachable — fall through to browser-side geocoding.
    }
  }

  // 2. Browser-side Nominatim (with street-fragment post-filter).
  try {
    const url = new URL("https://nominatim.openstreetmap.org/search");
    url.searchParams.set("q", q);
    url.searchParams.set("format", "json");
    url.searchParams.set("limit", "10");
    url.searchParams.set("countrycodes", "us");
    url.searchParams.set("addressdetails", "1");
    const resp = await fetch(url.toString(), {
      headers: { "User-Agent": "LivabilityRiskEngine/1.0 (us-mvp)" },
      cache: "no-store",
    });
    if (resp.ok) {
      const suggestions = _parseNominatim((await resp.json()) as NominatimItem[], streetFrag);
      if (suggestions.length) return suggestions;
    }
  } catch { /* fall through */ }

  // 3. Browser-side Photon fallback (with street-fragment post-filter).
  try {
    const url = new URL("https://photon.komoot.io/api/");
    url.searchParams.set("q", q);
    url.searchParams.set("limit", "10");
    url.searchParams.set("lang", "en");
    const resp = await fetch(url.toString(), { cache: "no-store" });
    if (resp.ok) {
      return _parsePhoton(((await resp.json()) as { features: PhotonFeature[] }).features ?? [], streetFrag);
    }
  } catch { /* */ }

  return [];
}

/**
 * Build a URL for the export endpoints (/export/csv or /export/pdf).
 * Returns an empty string if the backend is not configured.
 */
export function getExportUrl(type: "csv" | "pdf", address: string): string {
  const apiBaseUrl = getApiBaseUrl();
  if (!apiBaseUrl) return "";
  const url = buildApiUrl(`/export/${type}`);
  url.searchParams.set("address", address);
  return url.toString();
}

// ── Watchlist / Monitor this address ─────────────────────────────────────────
export type WatchRequest = {
  email: string;
  address: string;
  threshold: number; // 0–100
};

export type WatchResponse = {
  id: number | null;
  email: string;
  address: string;
  threshold: number;
  token: string | null;
  /** True when the backend accepted the request but the DB is not yet live. */
  demo?: boolean;
  message?: string;
};

/**
 * Subscribe an email to score-change alerts for an address.
 *
 * When the DB is not configured the backend returns a demo-success 200.
 * When the frontend has no API URL at all, a client-side demo response is
 * returned — the form always completes so email capture works on the free tier.
 * Actual alert email delivery is gated behind the Pro plan.
 */
export async function subscribeWatch(
  req: WatchRequest,
  backendToken?: string | null,
): Promise<WatchResponse> {
  const apiBaseUrl = getApiBaseUrl();

  if (!apiBaseUrl) {
    // No backend wired up — return a client-side demo response.
    return {
      id: null,
      email: req.email,
      address: req.address,
      threshold: req.threshold,
      token: null,
      demo: true,
      message: "Noted. Connect a backend to enable live alert delivery.",
    };
  }

  const url = buildApiUrl("/watchlist");
  const authHeaders = backendToken ? getAuthHeaders(backendToken) : await getSessionAuthHeaders();
  const resp = await fetch(url.toString(), {
    method: "POST",
    headers: { "Content-Type": "application/json", ...authHeaders },
    body: JSON.stringify(req),
    cache: "no-store",
  });

  if (!resp.ok) {
    const data = await resp.json().catch(() => ({})) as { detail?: string };
    throw new ApiError(data.detail ?? `Could not set up alert (${resp.status}).`);
  }

  return (await resp.json()) as WatchResponse;
}

export type SaveReportResponse = {
  report_id: string;
};

export type FetchReportResponse = ScoreResponse & {
  report_id: string;
  created_at: string;
};

/**
 * Save a score result to the backend and return a shareable report_id.
 * Throws ApiError if the backend is unreachable or DB is not configured.
 */
export async function saveReport(
  score: ScoreResponse,
  backendToken?: string | null,
): Promise<SaveReportResponse> {
  const apiBaseUrl = getApiBaseUrl();
  if (!apiBaseUrl) {
    throw new ApiError("Backend not configured. Cannot save report.");
  }
  const url = buildApiUrl("/save");
  const authHeaders = backendToken ? getAuthHeaders(backendToken) : await getSessionAuthHeaders();
  const resp = await fetch(url.toString(), {
    method: "POST",
    headers: { "Content-Type": "application/json", ...authHeaders },
    body: JSON.stringify(score),
  });
  if (!resp.ok) {
    throw new ApiError(`Save failed: ${resp.status}`);
  }
  const saved = (await resp.json()) as SaveReportResponse;
  try {
    const existingRaw = window.localStorage.getItem("lre_saved_reports");
    const existing = existingRaw ? JSON.parse(existingRaw) : [];
    const next = [
      {
        report_id: saved.report_id,
        address: score.address,
        saved_livability_score: score.livability_score ?? null,
        saved_disruption_score: score.disruption_score,
        created_at: new Date().toISOString(),
      },
      ...existing,
    ].slice(0, 10);
    window.localStorage.setItem("lre_saved_reports", JSON.stringify(next));
  } catch {
    // localStorage is best-effort only.
  }
  return saved;
}

export type WatchlistEntry = {
  id: number;
  email: string;
  address: string;
  threshold: number;
  created_at: string;
  is_active: boolean;
};

export async function fetchWatchlist(backendToken: string): Promise<WatchlistEntry[]> {
  const resp = await fetch(buildApiUrl("/watchlist").toString(), {
    headers: getAuthHeaders(backendToken),
    cache: "no-store",
  });
  if (!resp.ok) return [];
  const data = await resp.json() as { entries?: WatchlistEntry[] };
  return data.entries ?? [];
}

export type DashboardResponse = {
  saved_reports: Array<{
    report_id: string;
    address: string;
    saved_disruption_score: number | null;
    saved_livability_score: number | null;
    created_at: string;
  }>;
  watchlist: Array<{
    id: number;
    address: string;
    threshold: number;
    current_livability_score: number | null;
    score_diff_since_saved: number | null;
    score_changed: boolean;
    created_at: string;
  }>;
};

export async function fetchDashboard(backendToken: string): Promise<DashboardResponse | null> {
  try {
    const resp = await fetch(buildApiUrl("/dashboard").toString(), {
      headers: getAuthHeaders(backendToken),
      cache: "no-store",
    });
    if (!resp.ok) return null;
    return (await resp.json()) as DashboardResponse;
  } catch {
    return null;
  }
}

/**
 * Fetch a previously saved report by its UUID.
 * Returns null when not found or the backend is unreachable.
 */
export async function fetchReport(reportId: string): Promise<FetchReportResponse | null> {
  const apiBaseUrl = getApiBaseUrl();
  if (!apiBaseUrl) return null;
  try {
    const url = buildApiUrl(`/report/${reportId}`);
    const resp = await fetch(url.toString(), { cache: "no-store" });
    if (!resp.ok) return null;
    return (await resp.json()) as FetchReportResponse;
  } catch {
    return null;
  }
}

export type HistoryEntry = {
  disruption_score: number;
  confidence: ConfidenceLevel;
  mode: string;
  scored_at: string;
};

export type HistoryResponse = {
  address: string;
  history: HistoryEntry[];
};

/**
 * Fetch recent score history for a given address.
 * Returns null when the backend is unreachable or not configured.
 * Returns an empty history array when DB is in demo mode.
 */
export async function fetchHistory(
  address: string,
  limit = 10,
): Promise<HistoryResponse | null> {
  const apiBaseUrl = getApiBaseUrl();
  if (!apiBaseUrl) return null;

  try {
    const url = buildApiUrl("/history");
    url.searchParams.set("address", address);
    url.searchParams.set("limit", String(limit));
    const resp = await fetch(url.toString(), { cache: "no-store" });
    if (!resp.ok) return null;
    return (await resp.json()) as HistoryResponse;
  } catch {
    return null;
  }
}

// Score history entry returned by /history (data-025).
export type ScoreHistoryEntry = {
  disruption_score: number;
  confidence: ConfidenceLevel;
  mode: ScoreMode;
  created_at: string | null;
};

// Neighborhood page types (data-026).
export type NeighborhoodProject = {
  project_id: string;
  source: string;
  title: string | null;
  impact_type: string | null;
  status: string;
  lat: number | null;
  lon: number | null;
  start_date: string | null;
  end_date: string | null;
};

export type NeighborhoodResponse = {
  name: string;
  slug: string;
  description: string;
  center: { lat: number; lon: number };
  project_count: number;
  projects: NeighborhoodProject[];
  mode: "live" | "demo";
  // Median disruption score for this neighborhood (calibrated static value
  // until live score_history aggregation is wired up).
  median_score?: number | null;
  // Number of real score_history records backing the median (0 in demo mode).
  sample_size?: number;
};

// ── Best Streets ─────────────────────────────────────────────────────────────

export type BestStreetsBlock = {
  block: string;
  avg_score: number;
  active_projects: number;
};

export type BestStreetsResponse = {
  slug: string;
  name: string;
  quietest_blocks: BestStreetsBlock[];
  busiest_blocks: BestStreetsBlock[];
  last_updated: string;
  mode: "live" | "demo";
  meta_description: string;
};

/**
 * Fetch best-streets block data for a neighborhood.
 * Called server-side from the /neighborhood/[slug]/best-streets page.
 * Returns null when the backend is unreachable.
 */
export async function fetchBestStreets(slug: string): Promise<BestStreetsResponse | null> {
  const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL;
  if (!apiBaseUrl) return null;
  try {
    const url = new URL(`/neighborhood/${slug}/best-streets`, apiBaseUrl);
    const resp = await fetch(url.toString(), { next: { revalidate: 86400 } });
    if (!resp.ok) return null;
    return (await resp.json()) as BestStreetsResponse;
  } catch {
    return null;
  }
}

// ── All known neighborhood slugs (mirrors _NEIGHBORHOODS in backend/app/main.py) ──
export const ALL_NEIGHBORHOOD_SLUGS = [
  "wicker-park", "logan-square", "river-north", "lincoln-park",
  "pilsen", "loop", "uptown", "bridgeport",
  "old-town", "gold-coast", "streeterville", "south-loop",
  "andersonville", "rogers-park", "bucktown", "ukrainian-village",
  "humboldt-park", "hyde-park", "ravenswood", "avondale",
] as const;

export type NeighborhoodSlug = typeof ALL_NEIGHBORHOOD_SLUGS[number];

// ── Neighborhood bbox map — mirrors the static config in backend/app/main.py ──
// Used client-side to detect which neighborhood a scored address falls within,
// without an extra round-trip to the server.
type NeighborhoodBbox = {
  min_lat: number; min_lon: number;
  max_lat: number; max_lon: number;
  name: string;
  center: { lat: number; lon: number };
};

export const NEIGHBORHOOD_BBOXES: Record<string, NeighborhoodBbox> = {
  "wicker-park":       { min_lat: 41.8990, min_lon: -87.6950, max_lat: 41.9180, max_lon: -87.6600, name: "Wicker Park",        center: { lat: 41.9088, lon: -87.6776 } },
  "logan-square":      { min_lat: 41.9100, min_lon: -87.7250, max_lat: 41.9330, max_lon: -87.6900, name: "Logan Square",       center: { lat: 41.9217, lon: -87.7082 } },
  "river-north":       { min_lat: 41.8850, min_lon: -87.6500, max_lat: 41.9030, max_lon: -87.6200, name: "River North",        center: { lat: 41.8940, lon: -87.6340 } },
  "lincoln-park":      { min_lat: 41.9100, min_lon: -87.6630, max_lat: 41.9380, max_lon: -87.6270, name: "Lincoln Park",       center: { lat: 41.9240, lon: -87.6450 } },
  "pilsen":            { min_lat: 41.8470, min_lon: -87.6850, max_lat: 41.8650, max_lon: -87.6430, name: "Pilsen",             center: { lat: 41.8560, lon: -87.6640 } },
  "loop":              { min_lat: 41.8740, min_lon: -87.6480, max_lat: 41.8920, max_lon: -87.6180, name: "The Loop",           center: { lat: 41.8827, lon: -87.6323 } },
  "uptown":            { min_lat: 41.9540, min_lon: -87.6680, max_lat: 41.9750, max_lon: -87.6390, name: "Uptown",             center: { lat: 41.9650, lon: -87.6540 } },
  "bridgeport":        { min_lat: 41.8250, min_lon: -87.6600, max_lat: 41.8460, max_lon: -87.6300, name: "Bridgeport",        center: { lat: 41.8350, lon: -87.6444 } },
  "old-town":          { min_lat: 41.9010, min_lon: -87.6490, max_lat: 41.9180, max_lon: -87.6260, name: "Old Town",           center: { lat: 41.9095, lon: -87.6373 } },
  "gold-coast":        { min_lat: 41.8940, min_lon: -87.6400, max_lat: 41.9110, max_lon: -87.6170, name: "Gold Coast",         center: { lat: 41.9026, lon: -87.6289 } },
  "streeterville":     { min_lat: 41.8840, min_lon: -87.6270, max_lat: 41.9000, max_lon: -87.6080, name: "Streeterville",      center: { lat: 41.8920, lon: -87.6180 } },
  "south-loop":        { min_lat: 41.8590, min_lon: -87.6430, max_lat: 41.8770, max_lon: -87.6140, name: "South Loop",         center: { lat: 41.8680, lon: -87.6280 } },
  "andersonville":     { min_lat: 41.9730, min_lon: -87.6700, max_lat: 41.9890, max_lon: -87.6450, name: "Andersonville",      center: { lat: 41.9810, lon: -87.6580 } },
  "rogers-park":       { min_lat: 41.9940, min_lon: -87.6810, max_lat: 42.0120, max_lon: -87.6550, name: "Rogers Park",        center: { lat: 42.0030, lon: -87.6690 } },
  "bucktown":          { min_lat: 41.9090, min_lon: -87.6980, max_lat: 41.9260, max_lon: -87.6720, name: "Bucktown",           center: { lat: 41.9170, lon: -87.6850 } },
  "ukrainian-village": { min_lat: 41.8870, min_lon: -87.6870, max_lat: 41.9030, max_lon: -87.6620, name: "Ukrainian Village",  center: { lat: 41.8950, lon: -87.6750 } },
  "humboldt-park":     { min_lat: 41.8910, min_lon: -87.7380, max_lat: 41.9090, max_lon: -87.7060, name: "Humboldt Park",      center: { lat: 41.9000, lon: -87.7220 } },
  "hyde-park":         { min_lat: 41.7840, min_lon: -87.6090, max_lat: 41.8060, max_lon: -87.5810, name: "Hyde Park",          center: { lat: 41.7950, lon: -87.5950 } },
  "ravenswood":        { min_lat: 41.9620, min_lon: -87.6860, max_lat: 41.9790, max_lon: -87.6610, name: "Ravenswood",         center: { lat: 41.9700, lon: -87.6740 } },
  "avondale":          { min_lat: 41.9360, min_lon: -87.7230, max_lat: 41.9540, max_lon: -87.6970, name: "Avondale",           center: { lat: 41.9450, lon: -87.7100 } },
};

export type NeighborhoodSlugInfo = { slug: string; name: string; exact: boolean };

/**
 * Determine which pre-defined Chicago neighborhood a lat/lon falls within.
 *
 * Strategy:
 *  1. Exact bbox containment → returns exact: true
 *  2. Nearest center within ~3 mi → returns exact: false (address is "near")
 *  3. Outside Chicago or >3 mi from any center → returns null
 */
export function detectNeighborhoodSlug(lat: number, lon: number): NeighborhoodSlugInfo | null {
  // 1. Exact bbox test
  for (const [slug, bb] of Object.entries(NEIGHBORHOOD_BBOXES)) {
    if (lat >= bb.min_lat && lat <= bb.max_lat && lon >= bb.min_lon && lon <= bb.max_lon) {
      return { slug, name: bb.name, exact: true };
    }
  }

  // 2. Nearest-center fallback (degrees, equirectangular approx)
  let nearest: { slug: string; name: string; dist: number } | null = null;
  for (const [slug, bb] of Object.entries(NEIGHBORHOOD_BBOXES)) {
    const dlat = lat - bb.center.lat;
    const dlon = (lon - bb.center.lon) * Math.cos((lat * Math.PI) / 180);
    const dist = Math.sqrt(dlat * dlat + dlon * dlon);
    if (!nearest || dist < nearest.dist) nearest = { slug, name: bb.name, dist };
  }
  // ~0.044° ≈ 3 miles at Chicago latitude
  if (nearest && nearest.dist <= 0.044) return { slug: nearest.slug, name: nearest.name, exact: false };

  return null;
}

/**
 * Fetch neighborhood disruption data by slug.
 * Returns null when the backend is unreachable or the neighborhood is not found.
 */
export async function fetchNeighborhood(slug: string): Promise<NeighborhoodResponse | null> {
  const apiBaseUrl = getApiBaseUrl();
  if (!apiBaseUrl) return null;
  try {
    const url = buildApiUrl(`/neighborhood/${slug}`);
    const resp = await fetch(url.toString(), { cache: "no-store" });
    if (!resp.ok) return null;
    return (await resp.json()) as NeighborhoodResponse;
  } catch {
    return null;
  }
}

/**
 * Fetch a score for a single address, forwarding a caller-supplied API key.
 * Used by the /bulk page to score many addresses on behalf of the user.
 * Throws ApiError on any non-200 response so the caller can record a per-row error.
 */
export async function fetchScoreWithKey(address: string, apiKey: string): Promise<ScoreResponse> {
  const apiBaseUrl = getApiBaseUrl();
  if (!apiBaseUrl) {
    throw new ApiError(
      "Backend URL is not configured. Set NEXT_PUBLIC_API_URL to enable bulk scoring.",
    );
  }
  const url = buildApiUrl("/score");
  url.searchParams.set("address", address);
  const headers: Record<string, string> = {};
  if (apiKey) headers["X-API-Key"] = apiKey;
  const resp = await fetch(url.toString(), { cache: "no-store", headers });
  if (!resp.ok) {
    const data = await resp.json().catch(() => ({})) as { detail?: string };
    throw new ApiError(data.detail ?? `Score request failed (${resp.status})`);
  }
  return (await resp.json()) as ScoreResponse;
}

export async function fetchScore(address: string): Promise<ScoreResult> {
  const apiBaseUrl = getApiBaseUrl();

  // No backend URL — throw so the caller surfaces a clear error rather than
  // silently showing demo data the user didn't ask for.
  if (!apiBaseUrl) {
    logFrontendFallback("frontend_api_not_configured", "NEXT_PUBLIC_API_URL not set");
    throw new ApiError(
      "Backend URL is not configured. Set NEXT_PUBLIC_API_URL to enable live scoring.",
    );
  }

  const url = buildApiUrl("/score");
  url.searchParams.set("address", address);

  let response: Response;
  try {
    response = await fetch(url.toString(), { cache: "no-store" });
  } catch (err) {
    logFrontendFallback("frontend_network_error", String(err));
    throw new ApiError("Backend is temporarily unreachable. Please try again.");
  }

  if (!response.ok) {
    console.warn(`[LRE] backend score request failed: status=${response.status}`);
    if (response.status === 404) {
      throw new ApiError("Address not found. Try including a ZIP code or nearby intersection.");
    }
    throw new ApiError(
      response.status >= 500
        ? "The scoring service returned an error. Try again in a moment."
        : `Scoring request failed (${response.status}).`,
    );
  }

  const score = (await response.json()) as ScoreResponse;
  if (score.fallback_reason) {
    console.log("[LRE] backend fallback_reason:", score.fallback_reason);
  }

  // When the backend explicitly marks this as demo, pass that through.
  // This is the backend's intentional decision (e.g. DB not yet configured).
  const source: ScoreSource = score.mode ?? "live";
  if (source === "demo") {
    return {
      score,
      source: "demo",
      note: score.fallback_reason === "db_not_configured"
        ? "Backend is live but the database is not yet connected — showing sample data."
        : undefined,
    };
  }
  return { score, source: "live" };
}

// ── Commute corridor scoring ──────────────────────────────────────────────────

export type CommuteSignal = {
  title: string | null;
  impact_type: string | null;
  lat: number | null;
  lon: number | null;
  source: string;
};

export type CommuteResponse = {
  home: string;
  work: string;
  commute_score: number;
  badge: "Low" | "Moderate" | "High";
  signals_count: number;
  signals: CommuteSignal[];
  transit_stations: Array<{ name: string; lat: number; lon: number }>;
  transit_alerts: CommuteSignal[];
  home_coords: { lat: number; lon: number } | null;
  work_coords: { lat: number; lon: number } | null;
  mode: "live" | "demo";
};

/**
 * Score the disruption along a commute corridor between two addresses.
 * POSTs to /commute with { home, work }.
 * Returns null when the backend is not configured.
 */
export async function fetchCommute(
  home: string,
  work: string,
): Promise<CommuteResponse> {
  const apiBaseUrl = getApiBaseUrl();
  if (!apiBaseUrl) {
    throw new ApiError("Backend not configured. Cannot score commute corridor.");
  }
  const url = buildApiUrl("/commute");
  const resp = await fetch(url.toString(), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ home, work }),
    cache: "no-store",
  });
  if (!resp.ok) {
    const data = await resp.json().catch(() => ({})) as { detail?: string };
    throw new ApiError(data.detail ?? `Commute scoring failed (${resp.status}).`);
  }
  return (await resp.json()) as CommuteResponse;
}


// ---------------------------------------------------------------------------
// Auth helpers  (data-045)
//
// These utilities attach the user's backend_token (from their NextAuth session)
// to API requests as a Bearer token, and expose typed wrappers for the
// /auth/* endpoints on the FastAPI backend.
//
// Usage (client component):
//   const { data: session } = useSession();
//   const headers = getAuthHeaders(session?.user?.backend_token);
// ---------------------------------------------------------------------------

/**
 * Build an Authorization header object from a backend JWT.
 * Returns an empty object when token is absent so callers can always spread it.
 */
export function getAuthHeaders(backendToken?: string | null): Record<string, string> {
  if (!backendToken) return {};
  return { Authorization: `Bearer ${backendToken}` };
}

async function getSessionAuthHeaders(): Promise<Record<string, string>> {
  try {
    const { getSession } = await import("next-auth/react");
    const session = await getSession();
    return getAuthHeaders(session?.user?.backend_token ?? null);
  } catch {
    return {};
  }
}

// Shape returned by /auth/register, /auth/login, /auth/google
export type AuthResponse = {
  account_id: number;
  email: string;
  display_name: string | null;
  token: string;
};

// Shape returned by /auth/me
export type AuthUser = {
  account_id: string;
  email: string;
  name: string | null;
};

/**
 * Fetch the current user's profile from the backend.
 * Returns null if the token is missing or invalid (unauthenticated).
 */
export async function fetchAuthMe(backendToken: string): Promise<AuthUser | null> {
  try {
    const resp = await fetch(buildApiUrl("/auth/me").toString(), {
      headers: getAuthHeaders(backendToken),
      cache: "no-store",
    });
    if (!resp.ok) return null;
    return (await resp.json()) as AuthUser;
  } catch {
    return null;
  }
}
